version: '3'

services:
  finances4u-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  finances4u-app:
    image: finances4u-img
    ports:
      - 3000:3000
